- src/api/rppd/content-types/rppd/schema.json
- src/components/rpb/rppd-quelle-component.json
- src/components/rppd/f1nc.json
- src/components/rppd/f1nd.json
- src/components/rppd/f1nn.json
- src/components/rppd/f1no.json
- src/components/rppd/f1nt.json
- src/components/rppd/f1nw.json
See:
https://jira.hbz-nrw.de/browse/RPB-74
https://jira.hbz-nrw.de/browse/RPB-81
> Update RPPD content type for data import (RPB-74, RPB-81)

- src/api/rpb-authority/content-types/rpb-authority/schema.json
- src/components/rpb-sw/f3n.json
- src/components/rpb-sw/f3r.json
See https://jira.hbz-nrw.de/browse/RPB-84
> Update `rpb-authority` content type for data import (RPB-84)

- src/api/article/content-types/article/schema.json
- src/api/independent-work/content-types/independent-work/schema.json
- src/components/rpb/biblio-vino.json
> Adjust f18_ to allow only-BiblioVino resources

- Dockerfile.dev
- README.md
Instead of manual install as described in https://github.com/hbz/strapi-rpb#plugin
> Install lookup plugin via Docker

- src/api/article/content-types/article/schema.json
- src/components/rpb/gesamttitel-component.json
See https://jira.hbz-nrw.de/browse/RPB-72
> Add `f77_` to article, remove `f85.f85u` from component (RPB-72)

- README.md
- config/middlewares.js
- docker-compose.yml
- package.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
Not tested yet (as i don't know how to test ...) but you might give it a try nonetheless.
> Start Strapi in dev mode with --watch-admin option

- src/components/rpb/rppd-quelle-component.json
- src/components/rpb/werke-component.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
- src/plugins/lookup/admin/src/index.js
See https://jira.hbz-nrw.de/browse/RPB-87
- Display label / info for URIs
- Link to the URIs field values
- Add option to make lookup fields editable
> Improve custom lookup field display and config (RPB-87)

- src/api/fachgebiet/content-types/fachgebiet/schema.json
- src/api/fachgebiet/controllers/fachgebiet.js
- src/api/fachgebiet/routes/fachgebiet.js
- src/api/fachgebiet/services/fachgebiet.js
- src/components/rppd/f1nw.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
- src/plugins/lookup/admin/src/index.js
See https://jira.hbz-nrw.de/browse/RPB-136
> Add `fachgebiete` content type and lookup (RPB-136)

- src/components/rppd/f1nn.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
- src/plugins/lookup/admin/src/index.js
See https://jira.hbz-nrw.de/browse/RPB-135
> Lookup improvements in RPPD form

- package.json
- src/api/person/content-types/person/lifecycles.js
- src/components/person/gnd-subject-category.json
- src/components/person/place-of-activity.json
- src/components/person/profession-or-occupation.json
- src/components/person/publication.json
- src/components/person/related-person.json
- src/components/person/source.json
See https://jira.hbz-nrw.de/browse/RPB-159
> Set labels in UI for RPPD components with lookup fields

- src/plugins/lookup/admin/src/components/Autocomplete/index.js
- src/plugins/lookup/server/services/lookup.js
See https://jira.hbz-nrw.de/browse/RPB-169
> Set up custom fields for GND and RPPD suggestions (RPB-169)

- src/admin/app.js
For articles, independent-works, and persons
See https://jira.hbz-nrw.de/browse/RPB-131
> Add JSON and OPAC links in informations injection zone (RPB-131)

- src/api/rpb-spatial/content-types/rpb-spatial/schema.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
See https://jira.hbz-nrw.de/browse/RPB-140
> Add `definition` in rpb-spatial schema, use in lookups (RPB-140)

- src/admin/app.js
- src/plugins/lookup/admin/src/pages/App/index.js
- src/plugins/lookup/admin/src/pages/LinkList/index.js
- src/plugins/lookup/server/services/lookup.js
See https://jira.hbz-nrw.de/browse/RPB-183
Build links to Strapi edit view for each item in list.
Display as links in HTML page.
> Inject link list button in `listView` `actions` zone (RPB-183)

- .gitignore
- src/plugins/lookup/package-lock.json
Fixes issue with incompatible newer dependency during `strapi build` (see [README](https://github.com/hbz/strapi-rpb#plugin)).
> Add `package-lock.json` for reproducible clean build

- src/api/article/content-types/article/schema.json
- src/api/independent-work/content-types/independent-work/schema.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
See https://jira.hbz-nrw.de/browse/RPB-200
> Fixes in RPB cataloging UI

- package.json
- src/admin/app.js
- src/plugins/lookup/admin/src/index.js
- src/plugins/lookup/admin/src/pages/LinkList/index.js
See https://jira.hbz-nrw.de/browse/RPB-216
> Upgrade Strapi to 4.25.13

- .gitignore
- src/api/article/content-types/article/lifecycles.js
- src/api/backupHelper.js
- src/api/independent-work/content-types/independent-work/lifecycles.js
See:
https://jira.hbz-nrw.de/browse/RPB-199
https://jira.hbz-nrw.de/browse/RPB-202
> Export on create & update, 1 file for each type (RPB-199, RPB-202)

- src/plugins/lookup/server/services/lookup.js
See https://jira.hbz-nrw.de/browse/RPB-214
> Add `id` query to lobid-resources lookup (RPB-214)

- src/api/article/content-types/article/schema.json
See https://jira.hbz-nrw.de/browse/RPB-215
> Make `bibliographicCitation` component repeatable (RPB-215)

- src/api/article/content-types/article/schema.json
- src/api/independent-work/content-types/independent-work/schema.json
See https://jira.hbz-nrw.de/browse/RPB-222
Deployment note: change base to `main` before deploying & merging.
> Add `hbzId` field to title data schemas (RPB-222)

- public/robots.txt
> Disallow all robots from the whole site

- src/api/person/content-types/person/schema.json
- src/components/person/gnd-subject-category.json
- src/components/person/place-of-activity.json
- src/components/person/profession-or-occupation.json
- src/components/person/publication.json
- src/components/person/related-person.json
- src/components/person/source.json
See https://jira.hbz-nrw.de/browse/RPB-217
> Set `detached` to `false` for all lookups in person type (RPB-217)

- docker-compose-prod.yml
See https://github.com/hbz/strapi-rpb/issues/68
Docs:
- https://docs.docker.com/engine/containers/resource_constraints/
- https://docs.docker.com/reference/compose-file/deploy/#resources
> Add limits for CPU and RAM usage by postgres container

- src/api/article/content-types/article/lifecycles.js
- src/api/independent-work/content-types/independent-work/lifecycles.js
- src/plugins/lookup/admin/src/index.js
See https://jira.hbz-nrw.de/browse/RPB-227
> Misc cataloging issues

- src/api/article/content-types/article/lifecycles.js
- src/api/backupHelper.js
- src/api/indexHelper.js
- src/api/rpb-authority/content-types/rpb-authority/lifecycles.js
See https://jira.hbz-nrw.de/browse/RPB-230
> Handle deletions: write to file, send index DELETE (RPB-230)

- src/api/article/content-types/article/lifecycles.js
To see values in list view dropdowns on new entries
See https://jira.hbz-nrw.de/browse/RPB-210
> Set up `afterFindMany` hook for labels in list view (RPB-210)

- src/api/independent-work/content-types/independent-work/lifecycles.js
- src/components/rpb/in-series.json
- src/components/rpb/volume-in.json
See https://jira.hbz-nrw.de/browse/RPB-239
> Updates for independent works cataloging (RPB-239)

- README.md
- docker-compose-prod.yml
- docker-compose-test.yml
- docker-compose.yml
- Raised CPU and RAM for container
- Set timeout for postgresql statements, this should prevent 100% CPU usage over a long period caused by complex SELECT queries
- Add Adminer, a GUI for databases
> 246 high cpu usage

- src/components/rpb/volume-in.json
See https://jira.hbz-nrw.de/browse/RPB-256
> Remove `volumeIn.sortBy` from independent-works schema (RPB-256)

- src/api/labelHelper.js
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
See https://jira.hbz-nrw.de/browse/RPB-294
> Don't throw errors on non-OK fetch response, log message (RPB-294)

- src/components/rpb/bibliographic-citation.json
- src/plugins/lookup/admin/src/components/Autocomplete/index.js
- src/plugins/lookup/admin/src/index.js
See https://jira.hbz-nrw.de/browse/RPB-302
> Add `RPB-Titeldaten` to article source lookups (RPB-302)
